### ISSUE TITLE
Meta: Implement DTLS

### ISSUE THREAD

**Issue by willscott** [refraction-networking/dtls#1]
* [ ] 4.1 Record Layer - Sequence Number
  * [ ] 4.1.1 Transport Layer Mapping - record sizing
  * [ ] 4.1.2 Record Payload Protection - MAC; Anti-replay; Invalid records
* [ ] 4.2 Handshake
  * [ ] 4.2.1 Stateless cookie exchange
  * [ ] 4.2.3 Handle message loss / reordering / fragmentation
  * [ ] 4.2.4 retransmission timers
  * [ ] 4.2.5 ChangeCipherSpec
  * [ ] 4.2.6 CertificateVerify

**Comment by sergeyfrolov** [comment]
* [ ] 3.1. Loss-Insensitive Messaging
 * [ ] 3.2. Providing Reliability for Handshake
   * [ ] 3.2.1. Packet Loss
   * [ ] 3.2.2. Reordering
   * [ ] 3.2.3. Message Size
 * [ ] 3.3. Replay Detection
